# Generated by Django 5.1.6 on 2025-03-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
    ]
